
export const CHANGE_UNIT = 'CHANGE_UNIT';
export const ORIGINAL_GRAVITY = 'ORIGINAL_GRAVITY';
export const FINAL_GRAVITY = 'FINAL_GRAVITY';
export const BOILING_TIME = 'BOILING_TIME';
export const VOLUME = 'VOLUME';
export const FLAMEOUT = 'FLAMEOUT';
export const FLAMEOUT_TEMP = 'FLAMEOUT_TEMP';
export const NEW_HOPS_ADDITION = 'NEW_HOPS_ADDITION';
export const REMOVE_HOPS_ADDITION = 'REMOVE_HOPS_ADDITION';
export const CHANGE_HOPS_AMOUNT = 'CHANGE_HOPS_AMOUNT';
export const CHANGE_HOPS_ALPHA = 'CHANGE_HOPS_ALPHA';
export const CHANGE_HOPS_BOIL = 'CHANGE_HOPS_BOIL';
export const CHANGE_HOPS_FORM = 'CHANGE_HOPS_FORM';