name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: "github-pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3

      - name: Setup dx cli
        run: |
          curl -sSL https://dioxus.dev/install.sh | bash

      - name: Check format
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-features -- -D warnings
